#!/bin/bash
# startup script starts all the services on the container required to
# run the lab 

# Usage of the Script 

# To use startup.sh, run the command
# ./scripts/startup.sh

# starts the Apache service
#!/bin/bash
tomcat7_status=$(service tomcat7 status)
echo $tomcat7_status
if [[ "$tomcat7_status" == *"running"* ]];  then
    echo "tomcat7 is running"
elif [[ "$tomcat7_status" == *"stop"* ]];  then
    echo "tomcat7 is not running"
    service tomcat7 start
fi

mysql_status=$(service mysql status)
echo $mysql_status
if [[ "$mysql_status" == *"running"* ]];  then
    echo "Mysql is running"
elif [[ "$mysql_status" == *"stop"* ]];  then
    echo "mysql is not running"
    service mysql start
fi

apache2_status=$(service apache2 status)
echo $apache2_status
if [[ "$apache2_status" == *"running"* ]];  then
    echo "apache2 is running"
elif [[ "$apache2_status" == *"stop"* ]];  then
    echo "apache2 is not running"
    service apache2 start
fi

exit 0;
