name: testing github actions
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if owner
        run: |
          if [ "${{ github.actor }}" == "${{ github.repository_owner }}" ]; then
            echo "Running the workflow as the owner."
          else
            echo "You are not the owner of the repository. Workflow execution not allowed."
            exit 1
          fi
      - uses: actions/checkout@v3
      - name: Run make in src directory
        run: |
          cd src
          make -f ./makefile
